### ISSUE TITLE
Bug when signing up to Cakework through email address

### ISSUE THREAD

**Issue by mmahmad** [usecakework/cakework#2]
I was following the [Getting Started](https://docs.cakework.com/gettingstarted) doc when I got an error in the terminal during signup with my email address:

```
(base) $ cakework cakework signup
User code: <code>
Error signing up : Error getting user details.404 Not Found
```

I was still able to continue to deploy and run the task successfully in the tutorial, so, seems to be a false error.

**Comment by mmahmad** [comment]
I realized it may be because new email signups require confirmation. If that's the case, it would be helpful to print a message in the CLI saying that the user needs to check their email for a confirmation link, instead of throwing a 404 error.

Also, this makes wonder how I was able to deploy and run without confirming my email. Maybe it's a TODO for later...? Anyway, thought I'd mention it.

**Comment by jessie-young** [comment]
Hey Mohammad! Thanks for checking it out - to help me reproduce the error, could you paste (or send via discord) the contents of your ~/.cakework/config.json?

**Comment by mmahmad** [comment]
Sure, I'm traveling today. Will share by tonight hopefully.

**Comment by eric-cakework** [comment]
It was a spurious error message which is how it still worked :). Fixed in the latest build!
